/**
 * export the module via AMD, CommonJS or as a browser global
 * Export code from https://github.com/umdjs/umd/blob/master/returnExports.js
 */
;(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(factory)
    } else if (typeof exports === 'object') {
        /**
         * Node. Does not work with strict CommonJS, but
         * only CommonJS-like environments that support module.exports,
         * like Node.
         */
        module.exports = factory()
    } else {
        // Browser globals (root is window)
        factory()(root.lunr);
    }
}(this, function () {
    /**
     * Just return a value to define the module export.
     * This example returns an object, but the module
     * can return a function as the exported value.
     */
    return function(lunr) {
        /* throw error if lunr is not yet included */
        if ('undefined' === typeof lunr) {
            throw new Error('Lunr is not present. Please include / require Lunr before this script.');
        }

        /* throw error if lunr stemmer support is not yet included */
        if ('undefined' === typeof lunr.stemmerSupport) {
            throw new Error('Lunr stemmer support is not present. Please include / require Lunr stemmer support before this script.');
        }

        /*
         * Like Japanese, need to set the tokenizer in a special way
         */
        var isLunr2 = lunr.version[0] == "2";

        /* register specific locale function */
        lunr.zh = function () {
            this.pipeline.reset();
            this.pipeline.add(
                lunr.zh.trimmer,
                lunr.zh.stopWordFilter,
                lunr.zh.stemmer
            );

          if(isLunr2){
            this.tokenizer = lunr.zh.tokenizer;
          }else{
            if (lunr.tokenizer) { // for lunr version 0.6.0
              lunr.tokenizer = lunr.zh.tokenizer;
            }
            if (this.tokenizerFn) { // for lunr version 0.7.0 -> 1.0.0
              this.tokenizerFn = lunr.zh.tokenizer;
            }
          }

//            // for lunr version 2
//            // this is necessary so that every searched word is also stemmed before
//            // in lunr <= 1 this is not needed, as it is done using the normal pipeline
//            if (this.searchPipeline) {
//                this.searchPipeline.reset();
//                this.searchPipeline.add(lunr.zh.stemmer)
//            }
        };

      lunr.zh.tokenizer = function(obj){
        //remove all embed tag (z-...)
        obj = obj.replace(/#z-\S+/g, '');
        const pattern = new RegExp(/([A-zÀ-ÿ-]+|[0-9._]+|.|!|\?|'|"|:|;|,|-)/i);
        const results = obj.split(pattern).filter(e => e !== '' && e !== ' ');
        return results;
      };

        /* lunr trimmer function */
//        lunr.zh.wordCharacters = "{{wordCharacters}}";
//        lunr.zh.trimmer = lunr.trimmerSupport.generateTrimmer(lunr.zh.wordCharacters);
//
//        lunr.Pipeline.registerFunction(lunr.zh.trimmer, 'trimmer-zh');
//        lunr.zh.trimmer = (function() {
//          /* TODO stemmer  */
//          return function(word) {
//            return word;
//          }
//        })();

        /* lunr trimmer function */
        lunr.zh.trimmer = (function() {
          /* TODO stemmer  */
          return function(word) {
            return word
              .replace(/^[0-9.-]+$/, "")
              .replace(/^\s+/,'')
              .replace(/\s+$/, '')
              .replace(/^[\$\uFFE5\^\+=`~<>{}\[\]|\u3000-\u303F!-#%-\x2A,-/:;\x3F@\x5B-\x5D_\x7B}\u00A1\u00A7\u00AB\u00B6\u00B7\u00BB\u00BF\u037E\u0387\u055A-\u055F\u0589\u058A\u05BE\u05C0\u05C3\u05C6\u05F3\u05F4\u0609\u060A\u060C\u060D\u061B\u061E\u061F\u066A-\u066D\u06D4\u0700-\u070D\u07F7-\u07F9\u0830-\u083E\u085E\u0964\u0965\u0970\u0AF0\u0DF4\u0E4F\u0E5A\u0E5B\u0F04-\u0F12\u0F14\u0F3A-\u0F3D\u0F85\u0FD0-\u0FD4\u0FD9\u0FDA\u104A-\u104F\u10FB\u1360-\u1368\u1400\u166D\u166E\u169B\u169C\u16EB-\u16ED\u1735\u1736\u17D4-\u17D6\u17D8-\u17DA\u1800-\u180A\u1944\u1945\u1A1E\u1A1F\u1AA0-\u1AA6\u1AA8-\u1AAD\u1B5A-\u1B60\u1BFC-\u1BFF\u1C3B-\u1C3F\u1C7E\u1C7F\u1CC0-\u1CC7\u1CD3\u2010-\u2027\u2030-\u2043\u2045-\u2051\u2053-\u205E\u207D\u207E\u208D\u208E\u2329\u232A\u2768-\u2775\u27C5\u27C6\u27E6-\u27EF\u2983-\u2998\u29D8-\u29DB\u29FC\u29FD\u2CF9-\u2CFC\u2CFE\u2CFF\u2D70\u2E00-\u2E2E\u2E30-\u2E3B\u3001-\u3003\u3008-\u3011\u3014-\u301F\u3030\u303D\u30A0\u30FB\uA4FE\uA4FF\uA60D-\uA60F\uA673\uA67E\uA6F2-\uA6F7\uA874-\uA877\uA8CE\uA8CF\uA8F8-\uA8FA\uA92E\uA92F\uA95F\uA9C1-\uA9CD\uA9DE\uA9DF\uAA5C-\uAA5F\uAADE\uAADF\uAAF0\uAAF1\uABEB\uFD3E\uFD3F\uFE10-\uFE19\uFE30-\uFE52\uFE54-\uFE61\uFE63\uFE68\uFE6A\uFE6B\uFF01-\uFF03\uFF05-\uFF0A\uFF0C-\uFF0F\uFF1A\uFF1B\uFF1F\uFF20\uFF3B-\uFF3D\uFF3F\uFF5B\uFF5D\uFF5F-\uFF65]+/, '')
              .replace(/[\$\uFFE5\^\+=`~<>{}\[\]|\u3000-\u303F!-#%-\x2A,-/:;\x3F@\x5B-\x5D_\x7B}\u00A1\u00A7\u00AB\u00B6\u00B7\u00BB\u00BF\u037E\u0387\u055A-\u055F\u0589\u058A\u05BE\u05C0\u05C3\u05C6\u05F3\u05F4\u0609\u060A\u060C\u060D\u061B\u061E\u061F\u066A-\u066D\u06D4\u0700-\u070D\u07F7-\u07F9\u0830-\u083E\u085E\u0964\u0965\u0970\u0AF0\u0DF4\u0E4F\u0E5A\u0E5B\u0F04-\u0F12\u0F14\u0F3A-\u0F3D\u0F85\u0FD0-\u0FD4\u0FD9\u0FDA\u104A-\u104F\u10FB\u1360-\u1368\u1400\u166D\u166E\u169B\u169C\u16EB-\u16ED\u1735\u1736\u17D4-\u17D6\u17D8-\u17DA\u1800-\u180A\u1944\u1945\u1A1E\u1A1F\u1AA0-\u1AA6\u1AA8-\u1AAD\u1B5A-\u1B60\u1BFC-\u1BFF\u1C3B-\u1C3F\u1C7E\u1C7F\u1CC0-\u1CC7\u1CD3\u2010-\u2027\u2030-\u2043\u2045-\u2051\u2053-\u205E\u207D\u207E\u208D\u208E\u2329\u232A\u2768-\u2775\u27C5\u27C6\u27E6-\u27EF\u2983-\u2998\u29D8-\u29DB\u29FC\u29FD\u2CF9-\u2CFC\u2CFE\u2CFF\u2D70\u2E00-\u2E2E\u2E30-\u2E3B\u3001-\u3003\u3008-\u3011\u3014-\u301F\u3030\u303D\u30A0\u30FB\uA4FE\uA4FF\uA60D-\uA60F\uA673\uA67E\uA6F2-\uA6F7\uA874-\uA877\uA8CE\uA8CF\uA8F8-\uA8FA\uA92E\uA92F\uA95F\uA9C1-\uA9CD\uA9DE\uA9DF\uAA5C-\uAA5F\uAADE\uAADF\uAAF0\uAAF1\uABEB\uFD3E\uFD3F\uFE10-\uFE19\uFE30-\uFE52\uFE54-\uFE61\uFE63\uFE68\uFE6A\uFE6B\uFF01-\uFF03\uFF05-\uFF0A\uFF0C-\uFF0F\uFF1A\uFF1B\uFF1F\uFF20\uFF3B-\uFF3D\uFF3F\uFF5B\uFF5D\uFF5F-\uFF65]+$/, '')
              .toLowerCase();
          }
        })();

        /* lunr stemmer function */
//        lunr.zh.stemmer = (function() {
//          /* TODO stemmer  */
//          return function(word) {
//            return word;
//          }
//        })();
        lunr.zh.stemmer = lunr.stemmer;

        lunr.Pipeline.registerFunction(lunr.zh.stemmer, 'stemmer-zh');

        lunr.zh.stopWordFilter = lunr.generateStopWordFilter([
          "a",
          "able",
          "about",
          "across",
          "after",
          "all",
          "almost",
          "also",
          "am",
          "among",
          "an",
          "and",
          "any",
          "are",
          "as",
          "at",
          "be",
          "because",
          "been",
          "but",
          "by",
          "can",
          "cannot",
          "could",
          "dear",
          "did",
          "do",
          "does",
          "either",
          "else",
          "ever",
          "every",
          "for",
          "from",
          "get",
          "got",
          "had",
          "has",
          "have",
          "he",
          "her",
          "hers",
          "him",
          "his",
          "how",
          "however",
          "i",
          "if",
          "in",
          "into",
          "is",
          "it",
          "its",
          "just",
          "least",
          "let",
          "like",
          "likely",
          "may",
          "me",
          "might",
          "most",
          "must",
          "my",
          "neither",
          "no",
          "nor",
          "not",
          "of",
          "off",
          "often",
          "on",
          "only",
          "or",
          "other",
          "our",
          "own",
          "rather",
          "said",
          "say",
          "says",
          "she",
          "should",
          "since",
          "so",
          "some",
          "than",
          "that",
          "the",
          "their",
          "them",
          "then",
          "there",
          "these",
          "they",
          "this",
          "tis",
          "to",
          "too",
          "twas",
          "us",
          "wants",
          "was",
          "we",
          "were",
          "what",
          "when",
          "where",
          "which",
          "while",
          "who",
          "whom",
          "why",
          "will",
          "with",
          "would",
          "yet",
          "you",
          "your",
          "above",
          "according",
          "accordingly",
          "actually",
          "afterwards",
          "again",
          "against",
          "ain't",
          "allow",
          "allows",
          "alone",
          "along",
          "already",
          "although",
          "always",
          "amongst",
          "another",
          "anybody",
          "anyhow",
          "anyone",
          "anything",
          "anyway",
          "anyways",
          "anywhere",
          "apart",
          "appear",
          "appreciate",
          "appropriate",
          "aren't",
          "around",
          "a's",
          "aside",
          "ask",
          "asking",
          "associated",
          "available",
          "away",
          "awfully",
          "became",
          "become",
          "becomes",
          "becoming",
          "before",
          "beforehand",
          "behind",
          "being",
          "believe",
          "below",
          "beside",
          "besides",
          "best",
          "better",
          "between",
          "beyond",
          "both",
          "brief",
          "came",
          "cant",
          "can't",
          "cause",
          "causes",
          "certain",
          "certainly",
          "changes",
          "clearly",
          "c'mon",
          "co",
          "com",
          "come",
          "comes",
          "concerning",
          "consequently",
          "consider",
          "considering",
          "contain",
          "containing",
          "contains",
          "corresponding",
          "couldn't",
          "course",
          "c's",
          "currently",
          "definitely",
          "described",
          "despite",
          "didn't",
          "different",
          "doesn't",
          "doing",
          "done",
          "don't",
          "down",
          "downwards",
          "during",
          "each",
          "edu",
          "eg",
          "eight",
          "elsewhere",
          "enough",
          "entirely",
          "especially",
          "et",
          "etc",
          "even",
          "everybody",
          "everyone",
          "everything",
          "everywhere",
          "ex",
          "exactly",
          "example",
          "except",
          "far",
          "few",
          "fifth",
          "first",
          "five",
          "followed",
          "following",
          "follows",
          "former",
          "formerly",
          "forth",
          "four",
          "further",
          "furthermore",
          "gets",
          "getting",
          "given",
          "gives",
          "go",
          "goes",
          "going",
          "gone",
          "gotten",
          "greetings",
          "hadn't",
          "happens",
          "hardly",
          "hasn't",
          "haven't",
          "having",
          "hello",
          "help",
          "hence",
          "here",
          "hereafter",
          "hereby",
          "herein",
          "here's",
          "hereupon",
          "herself",
          "he's",
          "hi",
          "himself",
          "hither",
          "hopefully",
          "howbeit",
          "i'd",
          "ie",
          "ignored",
          "i'll",
          "i'm",
          "immediate",
          "inasmuch",
          "inc",
          "indeed",
          "indicate",
          "indicated",
          "indicates",
          "inner",
          "insofar",
          "instead",
          "inward",
          "isn't",
          "it'd",
          "it'll",
          "it's",
          "itself",
          "i've",
          "keep",
          "keeps",
          "kept",
          "know",
          "known",
          "knows",
          "last",
          "lately",
          "later",
          "latter",
          "latterly",
          "less",
          "lest",
          "let's",
          "liked",
          "little",
          "look",
          "looking",
          "looks",
          "ltd",
          "mainly",
          "many",
          "maybe",
          "mean",
          "meanwhile",
          "merely",
          "more",
          "moreover",
          "mostly",
          "much",
          "myself",
          "name",
          "namely",
          "nd",
          "near",
          "nearly",
          "necessary",
          "need",
          "needs",
          "never",
          "nevertheless",
          "new",
          "next",
          "nine",
          "nobody",
          "non",
          "none",
          "noone",
          "normally",
          "nothing",
          "novel",
          "now",
          "nowhere",
          "obviously",
          "oh",
          "ok",
          "okay",
          "old",
          "once",
          "one",
          "ones",
          "onto",
          "others",
          "otherwise",
          "ought",
          "ours",
          "ourselves",
          "out",
          "outside",
          "over",
          "overall",
          "particular",
          "particularly",
          "per",
          "perhaps",
          "placed",
          "please",
          "plus",
          "possible",
          "presumably",
          "probably",
          "provides",
          "que",
          "quite",
          "qv",
          "rd",
          "re",
          "really",
          "reasonably",
          "regarding",
          "regardless",
          "regards",
          "relatively",
          "respectively",
          "right",
          "same",
          "saw",
          "saying",
          "second",
          "secondly",
          "see",
          "seeing",
          "seem",
          "seemed",
          "seeming",
          "seems",
          "seen",
          "self",
          "selves",
          "sensible",
          "sent",
          "serious",
          "seriously",
          "seven",
          "several",
          "shall",
          "shouldn't",
          "six",
          "somebody",
          "somehow",
          "someone",
          "something",
          "sometime",
          "sometimes",
          "somewhat",
          "somewhere",
          "soon",
          "sorry",
          "specified",
          "specify",
          "specifying",
          "still",
          "sub",
          "such",
          "sup",
          "sure",
          "take",
          "taken",
          "tell",
          "tends",
          "th",
          "thank",
          "thanks",
          "thanx",
          "thats",
          "that's",
          "theirs",
          "themselves",
          "thence",
          "thereafter",
          "thereby",
          "therefore",
          "therein",
          "theres",
          "there's",
          "thereupon",
          "they'd",
          "they'll",
          "they're",
          "they've",
          "think",
          "third",
          "thorough",
          "thoroughly",
          "those",
          "though",
          "three",
          "through",
          "throughout",
          "thru",
          "thus",
          "together",
          "took",
          "toward",
          "towards",
          "tried",
          "tries",
          "truly",
          "try",
          "trying",
          "t's",
          "twice",
          "two",
          "un",
          "under",
          "unfortunately",
          "unless",
          "unlikely",
          "until",
          "unto",
          "up",
          "upon",
          "use",
          "used",
          "useful",
          "uses",
          "using",
          "usually",
          "value",
          "various",
          "very",
          "via",
          "viz",
          "vs",
          "want",
          "wasn't",
          "way",
          "we'd",
          "welcome",
          "well",
          "we'll",
          "went",
          "we're",
          "weren't",
          "we've",
          "whatever",
          "what's",
          "whence",
          "whenever",
          "whereafter",
          "whereas",
          "whereby",
          "wherein",
          "where's",
          "whereupon",
          "wherever",
          "whether",
          "whither",
          "whoever",
          "whole",
          "who's",
          "whose",
          "willing",
          "wish",
          "within",
          "without",
          "wonder",
          "won't",
          "wouldn't",
          "yes",
          "you'd",
          "you'll",
          "you're",
          "yours",
          "yourself",
          "yourselves",
          "you've",
          "zero",
          "zt",
          "zz",
          "一",
          "与",
          "且",
          "个",
          "临",
          "为",
          "乃",
          "么",
          "之",
          "乎",
          "乘",
          "也",
          "了",
          "于",
          "从",
          "他",
          "以",
          "们",
          "任",
          "但",
          "何",
          "你",
          "依",
          "俺",
          "倘",
          "像",
          "兮",
          "其",
          "冒",
          "冲",
          "几",
          "凭",
          "则",
          "别",
          "到",
          "即",
          "又",
          "及",
          "另",
          "叫",
          "可",
          "各",
          "同",
          "向",
          "吓",
          "吗",
          "吧",
          "吱",
          "呀",
          "呃",
          "呕",
          "呗",
          "呜",
          "呢",
          "呵",
          "呸",
          "咋",
          "和",
          "咚",
          "咦",
          "咱",
          "咳",
          "哇",
          "哈",
          "哉",
          "哎",
          "哗",
          "哟",
          "哦",
          "哩",
          "哪",
          "哼",
          "唉",
          "啊",
          "啐",
          "啥",
          "啦",
          "喂",
          "喏",
          "嗬",
          "嗯",
          "嗳",
          "嘎",
          "嘘",
          "嘛",
          "嘻",
          "嘿",
          "因",
          "在",
          "地",
          "多",
          "她",
          "如",
          "宁",
          "它",
          "对",
          "将",
          "就",
          "尽",
          "己",
          "并",
          "归",
          "当",
          "彼",
          "往",
          "待",
          "得",
          "怎",
          "您",
          "我",
          "或",
          "所",
          "打",
          "把",
          "拿",
          "按",
          "据",
          "故",
          "既",
          "是",
          "替",
          "有",
          "望",
          "朝",
          "本",
          "来",
          "某",
          "此",
          "每",
          "比",
          "沿",
          "焉",
          "照",
          "用",
          "由",
          "的",
          "着",
          "矣",
          "离",
          "第",
          "等",
          "管",
          "纵",
          "经",
          "给",
          "者",
          "而",
          "能",
          "腾",
          "自",
          "至",
          "若",
          "虽",
          "被",
          "要",
          "让",
          "论",
          "该",
          "谁",
          "赶",
          "起",
          "趁",
          "跟",
          "较",
          "边",
          "过",
          "这",
          "连",
          "那",
          "阿",
          "除",
          "随",
          "靠",
          "顺",
        ]);

        lunr.Pipeline.registerFunction(lunr.zh.stopWordFilter, 'stopWordFilter-zh');
    };
}))
